### ISSUE TITLE
With R8 (proguard) enabled, all flags are returning default values.

### ISSUE THREAD

**Issue by valeriyo** [configcat/android-sdk#17]
### Describe the bug

Feature flags work in **debug** build, but in **release** (with "isMinifyEnabled = true") - all flags return default values.

**Comment by valeriyo** [comment]
I added a "keep all" rule in `proguard-rules.pro`:

```
-keep class com.configcat.** { *; }
-dontwarn org.slf4j.**
```

and **release** works now, however, this effectively disabled R8 for your library.

Please provide more specific rule(s) in the README.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, thank your for reporting! I'm going to create and include a consumer proguard file with the required rules.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, we released v7.1.0 that contains the consumer proguard rules, could you please check that it works on your end as expected? Thanks!

**Comment by valeriyo** [comment]
Appears to work for me, although my current usage is very basic (e.g. no percentage rollout stuff). Thanks!
