### ISSUE TITLE
forceRefresh() / forceRefreshAsync() swallow errors

### ISSUE THREAD

**Issue by valeriyo** [configcat/android-sdk#21]
I'd like to "force refresh" and know if it was succeeded or not. Should be easy, right? Not so. Both `forceRefresh()` and `forceRefreshAsync()` swallow errors and return nothing.

**Comment by z4kn4fein** [comment]
Hi @valeriyo, thank you for reporting! 
We are working on some improvements including this area. May I have some questions about your use case? Would an error event callback that you can subscribe to on SDK initialisation be an acceptable solution? Or is it important to you to get the error back with the return value of a direct call to `forceRefresh()`?

**Comment by valeriyo** [comment]
For a start, I am going with a manual refresh strategy, when the app starts. So it's important for me to know when `forceRefresh` failed, so that I can periodically retry.

**Comment by z4kn4fein** [comment]
Thank you for the insights, we'll include this improvement in the oncoming SDK developments.

**Comment by z4kn4fein** [comment]
This feature was released in `v8.0.0`
