### ISSUE TITLE
Does not work wth AGP 7.3.0 (which requires Android Studio Dolphin).

### ISSUE THREAD

**Issue by valeriyo** [configcat/android-sdk#22]
### Describe the bug

We recently upgraded to AGP 7.3.0 (https://developer.android.com/studio/releases/gradle-plugin#7-3-0) and configcat didn't work at all in release builds - very similar to https://github.com/configcat/android-sdk/issues/17 - all default values, no cached values or overrides.

So, in your "keep" rules:

```
-keep class com.configcat.Config { <fields>; }
-keep class com.configcat.Preferences { <fields>; }
-keep class com.configcat.Setting { <fields>; }
-keep class com.configcat.RolloutRule { <fields>; }
-keep class com.configcat.RolloutPercentageItem { <fields>; }
```

I replaced `<fields>` with wildcard `*`, and it worked just fine.

The new R8 used by AGP 7.3.0 must be doing more optimizations, and the previous rules are no longer sufficient.

Thanks.

**Comment by z4kn4fein** [comment]
Hi @valeriyo , thank you for the report! I've updated our rules and released in `v7.3.0`.
