### ISSUE TITLE
Cannot run unit tests directly in Android Studio

### ISSUE THREAD

**Issue by andrewreeman** [configcat/android-sdk#8]
### Describe the bug

Cannot run tests in Android Studio following instructions on CONTRIBUTING.md

Android Studio build is: 

_Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.github.leomillon.uuidgenerator, com.intellij.marketplace, com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown_

Gradle sync does not error.
Running `./gradlew test` from the terminal successfully runs all the tests

### To reproduce
This could be specific to Android Studio 4.2 on Mac.

1. Open the android-sdk project in Android Studio
2. Open Run menu
3. Select Run...
4. Select All in configcat-android-client
5. Clicking on the run button does nothing. Nothing appears in the event log.

### Expected behavior

All unit tests will be run from Android Studio

### Screenshots
Attached is the standard configuration created from following the instructions on the contributing doc.

![Screenshot 2021-05-14 at 09 27 27](https://user-images.githubusercontent.com/1423405/118243735-aae28c80-b496-11eb-98db-dcea9e573137.png)

![Screenshot 2021-05-14 at 09 27 35](https://user-images.githubusercontent.com/1423405/118243757-b03fd700-b496-11eb-9c7b-ace64ead32a1.png)

**Comment by z4kn4fein** [comment]
Thank you for reporting! We'll look into this and update the related guide accordingly.

**Comment by andrewreeman** [comment]
Thanks for that. Yes that works fine now. Managed to run the tests with no issue
